// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArG3ctP43_XjuEd7mCKQ6PwTvM_QxFyRI',
    appId: '1:291382142551:web:03f84f0c13e2ef8899a512',
    messagingSenderId: '291382142551',
    projectId: 'bitacora-28be4',
    authDomain: 'bitacora-28be4.firebaseapp.com',
    storageBucket: 'bitacora-28be4.firebasestorage.app',
    measurementId: 'G-5BRJY1CV7E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_eNIXKSKoCZAaBGxBskrGpNvI7BcvNTo',
    appId: '1:291382142551:android:ccabeff2fbdfe79399a512',
    messagingSenderId: '291382142551',
    projectId: 'bitacora-28be4',
    storageBucket: 'bitacora-28be4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArG3ctP43_XjuEd7mCKQ6PwTvM_QxFyRI',
    appId: '1:291382142551:web:c3d12b53cdfc291a99a512',
    messagingSenderId: '291382142551',
    projectId: 'bitacora-28be4',
    authDomain: 'bitacora-28be4.firebaseapp.com',
    storageBucket: 'bitacora-28be4.firebasestorage.app',
    measurementId: 'G-V4HTH7R6FJ',
  );
}
